[tool.mypy]
files = 'servctl'
strict = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
install_types = true
warn_redundant_casts = true
warn_unreachable = true
warn_return_any = true
show_error_context = true
show_column_numbers = true
pretty = true
warn_unused_configs = true
disallow_untyped_decorators = false

[[tool.mypy.overrides]]
module = [
		"ovh",
		"fabric.*",
		"giturlparse",
		"patchwork.*",
		"invocations.*",
		"invoke.*",
]
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "88"
