
- name: Setup Ruby dev tools
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "ruby{{ runtimes.ruby.version }}"
      - "ruby{{ runtimes.ruby.version }}-dev"
      - ri
      - ruby-bundler
  tags: ruby
