---
- name: install php-fpm
  package:
    name: "php{{ runtimes.php.version }}-fpm"
    state: present
  tags: php-fpm

- name: enable php-fpm
  service:
    name: "php{{ runtimes.php.version }}-fpm"
    state: started
    enabled: true
  tags: php-fpm
