---
- name: Install git
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - git-lfs
  tags: git

- name: add global dotfiles
  ansible.builtin.copy:
    src: "../template/etc/{{ item }}"
    dest: "/etc/apt/{{ item }}"
  with_items:
    - gitconfig
  tags: git

- name: create SSH certificat directories
  file:
    path: /var/www/.ssh
    state: directory
    mode: 0700
    owner: www-data
    group: www-data
  tags: git

- name: add Github public key
  known_hosts:
    path: /var/www/.ssh/known_hosts
    name: github.com
    key: "{{ item }}"
  with_items:
    - 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
  tags: git

- name: Fix ssh known_hosts ownership
  file:
    path: /var/www/.ssh/known_hosts
    mode: 0600
    owner: www-data
    group: www-data
  tags: git
