---
- name: setup python dev tools
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "python{{ runtimes.python.version }}"
      - "python{{ runtimes.python.version }}-venv"
      - "python{{ runtimes.python.version }}-dev"
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
      - libssl-dev
      - libffi-dev
      - libsqlite3-dev
      - libbz2-dev
      - libxml2-dev
      - liblzma-dev
      - pipenv
      - pipx
  tags: python

- name: install pip packages
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - poetry
    # - pipenv
    # - pipx
  tags: python
