---
- name: setup python dev tools
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3  # TODO python{3.9}
      - python3-pip
      - python3-venv
      - python3-dev
      - python3-virtualenv
  tags: python

- name: install pipenv
  pip:
    name: pipenv
    executable: pip3
  tags: python
