---
- name: Install uwsgi
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - uwsgi
      - uwsgi-emperor
      - uwsgi-plugin-python3
  tags: uwsgi

- name: Enable uwsgi
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - uwsgi
    - uwsgi-emperor
  tags: uwsgi
