---
- name: setup nodejs dev tools
  include_role:
    name: geerlingguy.nodejs
  vars:
    nodejs_version: "{{ runtimes.nodejs.version }}.x"
    # nodejs_npm_global_packages:
    #   - name: yarn

- name: setup nodejs yarn
  include_role:
    name: oefenweb.yarn
