---
roles:
  - src: geerlingguy.nodejs
  - src: geerlingguy.docker
  - src: geerlingguy.composer
  - src: ebbba.bigbluebutton
  - src: oefenweb.yarn
  - src: datadog.datadog

collections:
  - name: community.general
