---
- hosts: all
  become: true
  tasks:
    - name: setup security tools
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ufw
          - fail2ban
          - logwatch
          - unattended-upgrades

    - name: config ufw
      block:
      - ufw:
          policy: deny
      - ufw:
          logging: on
      - ufw:
          rule: allow
          port: 80
      - ufw:
          rule: allow
          port: 443
      - ufw:
          rule: limit
          port: 110  # our ssh port
          proto: tcp
      - ufw:
          state: enabled

    - name: config logwatch
      ansible.builtin.copy:
        src: ../template/etc/cron/00logwatch
        dest: /etc/cron.daily/00logwatch

    - name: config sysctl
      ansible.builtin.copy:
        src: ../template/etc/sysctl.conf
        dest: /etc/sysctl.conf
    - name: reload sysctl
      command: /sbin/sysctl -p

    - name: config unattended-upgrades
      ansible.builtin.copy:
        src: "../template/etc/apt/apt.conf.d/{{ item }}"
        dest: "/etc/apt/apt.conf.d/{{ item }}"
      with_items:
        - 10periodic
        - 50unattended-upgrades

    - name: enable security services
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - unattended-upgrades
        - ufw
        - fail2ban
