---
- name: config sysctl
  ansible.builtin.copy:
    src: ../template/etc/sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644

- name: reload sysctl
  ansible.builtin.command: /sbin/sysctl -p
