---
- name: setup security tools
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ufw

- name: config ufw
  block:
  - ufw:
      policy: deny
  - ufw:
      logging: on
  - ufw:
      rule: allow
      port: 80
  - ufw:
      rule: allow
      port: 443
  - ufw:
      rule: limit
      port: 110  # our ssh port
      proto: tcp
  - ufw:
      state: enabled

- name: enable security services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - ufw
